name: docker info

on:
  workflow_dispatch:


defaults:
  run:
    shell: bash

jobs:
  run:
    name: Run
    runs-on: ubuntu-22.04

    steps:
    - name: docker info
      run: |
        docker info
        