name: docker info

on:
  workflow_dispatch:
  
  pull_request:
    branches:
    - main


defaults:
  run:
    shell: bash

jobs:
  run:
    name: Run
    runs-on: ubuntu

    steps:
    - name: docker info
      run: |
        docker info
        
