name: docker info


on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  run:
    name: Run
    runs-on: ubuntu-22.04

    steps:
    - name: docker info
      run: |
        docker info
